// Barcha UI matnlari shu yerda. Keyin rus tili uchun strings.ru.ts qo'shiladi.
export const REGIONS = [
  "Toshkent shahri",
  "Toshkent viloyati",
  "Andijon",
  "Buxoro",
  "Fargʻona",
  "Jizzax",
  "Xorazm",
  "Namangan",
  "Navoiy",
  "Qashqadaryo",
  "Qoraqalpogʻiston",
  "Samarqand",
  "Sirdaryo",
  "Surxondaryo",
] as const;

export const INTERESTS = [
  { key: "tech", label: "Texnologiya" },
  { key: "business", label: "Tadbirkorlik" },
  { key: "languages", label: "Tillar" },
  { key: "science", label: "Fan" },
  { key: "art", label: "Sanʼat" },
  { key: "sport", label: "Sport" },
  { key: "volunteering", label: "Volontyorlik" },
  { key: "study-abroad", label: "Chet elda oʻqish" },
] as const;

export const ROLES = [
  "Dasturchi",
  "Dizayner",
  "Marketing",
  "Kontent / matn",
  "Video",
  "Menejer",
  "Boshqa",
] as const;

export const t = {
  meta: {
    title: "Yoshlar Base",
    description:
      "Yoshlar uchun digital home: klublar, tekshirilgan imkoniyatlar va g'oyadan jamoagacha.",
  },
  brand: "Yoshlar Base",
  sample: "NAMUNA",
  theme: {
    toDark: "Tungi rejimga o'tish",
    toLight: "Kunduzgi rejimga o'tish",
  },
  nav: {
    links: [
      { href: "#makonlar", label: "Makonlar" },
      { href: "#yol", label: "Qanday ishlaydi" },
      { href: "#xavfsizlik", label: "Xavfsizlik" },
    ],
    login: "Kirish",
  },
  hero: {
    title: "Yoshlarning o'z makoni",
    titleMuted: "qiziqishdan haqiqiy ishgacha",
    lead: "Klubga qo'shiling, ishonchli imkoniyatlarni toping, g'oyangizdan jamoa yig'ing. Qilganlaringiz profilingizda o'zi to'planadi.",
    primary: "Imkoniyatlarni ko'rish",
    secondary: "Telegram orqali kirish",
  },
  orbit: {
    line1: "Real ishga olib",
    line2: "boradigan",
    mark: "uchta makon",
    text: "Klublar, tekshirilgan imkoniyatlar va g'oyalar doskasi. Ilovada vaqt o'tkazish uchun emas, tashqariga chiqib ish qilish uchun.",
    cta: "Makonlarni ko'rish",
  },
  spaces: {
    pill: "Makonlar",
    line1: "Hammasi haqiqiy.",
    line2: "Hammasi tekshirilgan.",
  },
  flow: {
    line1: "Bitta harakat",
    line2: "keyingisini ochadi",
    text: "Klubdan boshlang. Qolganlari o'zi keladi.",
    root: "Real harakat",
    leaves: [
      { title: "Klubga qatnash", text: "QR bilan tasdiqlanadi" },
      { title: "Ariza topshir", text: "Rasmiy havola orqali" },
      { title: "G'oya qo'y", text: "Moderatsiyadan o'tadi" },
      { title: "Jamoa bo'l", text: "Qabul qilinsa aloqa ochiladi" },
    ],
  },
  safety: {
    pill: "Xavfsizlik",
    line1: "Ko'pchiligimiz",
    mark: "13-17",
    line2: "yoshdamiz.",
    items: [
      { title: "Telefon yo'q", text: "Faqat Telegram orqali kirasiz. Email va parol so'ralmaydi." },
      { title: "Ochiq profil yo'q", text: "Hech kim sizni qidirib topa olmaydi." },
      { title: "Yosh guruhi", text: "18 yoshgacha bo'lganlar 18+ bilan bog'lanmaydi." },
      { title: "To'liq o'chirish", text: "Akkaunt va ma'lumotlar bir bosishda o'chadi." },
    ],
    finTitle: "Birinchi qadamni bugun qiling",
    cta: "Telegram orqali boshlash",
    ctaSecondary: "Imkoniyatlarni ko'rish",
    finNote: "Parol, email va telefon raqami kerak emas.",
  },
  footer: "Yoshlar uchun digital home",
  app: {
    sampleNotice: "NAMUNA belgili qatorlar sinov uchun. Haqiqiy klub va imkoniyatlar tez orada qo'shiladi.",
    back: "Orqaga",
    report: "Xabar berish",
    tabs: [
      { href: "/asosiy", label: "Asosiy" },
      { href: "/klublar", label: "Klublar" },
      { href: "/imkoniyatlar", label: "Imkoniyatlar" },
      { href: "/miya", label: "MIYA" },
      { href: "/profil", label: "Profil" },
    ],
    profileLink: "Profilim",
    login: {
      title: "Telegram orqali kirish",
      lead: "Akkaunt Telegram ID'ingizga bog'lanadi. Birinchi kirishda bot 4 ta qisqa savol beradi, alohida ro'yxatdan o'tish yo'q.",
      cta: "Telegram'da ochish",
      noBot: "Bot hali ulanmagan. Tez orada ishlaydi.",
      steps: [
        { title: "Botni oching", text: "Tugma Telegram'dagi botimizni ochadi." },
        { title: "4 ta savolga javob bering", text: "Ism, yosh oralig'i, hudud va qiziqishlar." },
        { title: "Saytga qayting", text: "Bot havolasi sizni avtomatik kiritadi." },
      ],
      never: "Parol, email va telefon raqami so'ralmaydi.",
      home: "Bosh sahifaga",
      waitTitle: "Telegram'da tasdiqlang",
      waitText: "Botda «Start» ni bosing va savollarga javob bering. Tugagach, shu sahifa o'zi davom etadi.",
      openBot: "Botni ochish",
      waiting: "Telegram'dan javob kutilmoqda…",
    },
    home: {
      hello: "Salom",
      stats: { sessions: "sessiya", saved: "saqlangan", teams: "jamoa" },
      nextStep: "Keyingi qadam",
      today: "Bugun",
      tomorrow: "Ertaga",
      open: "Ochish",
      noClub: "Klubga qo'shiling",
      noClubSub: "Sessiyalar shu yerda chiqadi",
      week: "Bu hafta",
      weekDays: ["Ya", "Du", "Se", "Ch", "Pa", "Ju", "Sh"],
      legendSession: "sessiya",
      legendDeadline: "ariza muddati",
      spaces: "Bo'limlar",
      tiles: {
        clubs: (n: number) => `${n} ta klub`,
        opps: (n: number) => `${n} ta ochiq`,
        miya: (n: number) => `${n} ta g'oya`,
        profile: (n: number) => `${n} ta sessiya`,
      },
      deadlines: "Muddati yaqin",
      daysShort: "kun",
      lastDay: "oxirgi kun",
      ideas: "Yangi g'oyalar",
    },
    today: {
      hello: "Salom",
      lead: "Bugun nima qilsa bo'ladi:",
      next: "Keyingi sessiya",
      today: "Bugun",
      checkin: "QR bilan tasdiqlash",
      deadlines: "Muddati yaqin",
      deadlinesEmpty: "Saqlangan imkoniyat yo'q. Imkoniyatlar bo'limidan saqlab qo'ying.",
      ideas: "Sizga mos g'oyalar",
      all: "Hammasi",
      daysLeft: "kun qoldi",
      lastDay: "Bugun oxirgi kun",
      noClub: "Hali klubga qo'shilmagansiz",
      noClubText: "Klubga qo'shilsangiz, keyingi sessiya shu yerda chiqadi va kuni Telegram'da eslatma keladi.",
      toClubs: "Klublarni ko'rish",
      ideasEmpty: "Hozircha yangi g'oya yo'q.",
    },
    clubs: {
      title: "Klublar",
      lead: "Real uchrashuvlar, haqiqiy odamlar.",
      members: "a'zo",
      next: "Keyingi sessiya",
      join: "Qo'shilish",
      schedule: "Jadval",
      place: "Joy",
      organizer: "Tashkilotchi",
      past: "O'tgan sessiyalar",
      pastEmpty: "Hali sessiya bo'lmagan.",
      qrNote: "Sessiyada QR skanerlang: qatnashish profilga yoziladi.",
    },
    opps: {
      title: "Imkoniyatlar",
      lead: "Qo'lda tekshirilgan, rasmiy manba bilan.",
      all: "Hammasi",
      open: "Ochiq",
      closed: "Yopilgan",
      filterType: "Turi",
      filterStatus: "Holati",
      deadline: "Ariza oxirgi kuni",
      age: "yosh",
      verified: "Tekshirildi",
      official: "Rasmiy sahifaga o'tish",
      save: "Saqlash",
      eligibility: "Kimlar uchun",
      region: "Hudud",
      ageRange: "Yosh oralig'i",
      organizer: "Tashkilotchi",
      stale: "Xato yoki eskirganmi? Xabar bering",
      empty: "Bu filtr bo'yicha imkoniyat topilmadi.",
      closedNote: "Ariza qabul qilish tugagan.",
    },
    miya: {
      title: "MIYA",
      lead: "G'oya qo'ying, jamoa toping.",
      add: "G'oya qo'yish",
      moderation: "Har bir g'oya moderatsiyadan keyin ko'rinadi.",
      team: "Jamoa",
      roles: "Kerakli rollar",
      filled: "Band",
      open: "Bo'sh",
      join: "Qo'shilaman",
      ageGroup: "Yosh guruhi",
      problem: "Muammo",
      idea: "G'oya",
      safety: "Aloqa faqat qabul qilingach, o'z yosh guruhingizda.",
      form: {
        title: "Yangi g'oya",
        lead: "Qisqa va aniq yozing. G'oya moderatsiyadan o'tgach doskada ko'rinadi.",
        name: "G'oya nomi",
        namePh: "Masalan: Maktab uchun kitob almashish boti",
        problem: "Qanday muammoni hal qiladi?",
        problemPh: "Bir-ikki gap bilan",
        description: "Qanday ishlaydi?",
        descriptionPh: "Birinchi qadam nima bo'ladi?",
        roles: "Kimlar kerak?",
        roleOptions: ["Dasturchi", "Dizayner", "Montajchi", "Tashkilotchi", "Muallif", "Marketing"],
        submit: "Moderatsiyaga yuborish",
        later: "Yuborish M8 bosqichida ulanadi. Hozircha bu forma NAMUNA.",
      },
    },
    profile: {
      title: "Men nimalar qildim",
      private: "Profilingiz faqat sizga ko'rinadi.",
      sessions: "sessiya",
      clubs: "klub",
      teams: "jamoa",
      timeline: "Faoliyat",
      timelineNote: "Real harakatlardan o'zi yig'iladi.",
      settings: "Sozlamalar",
      interests: "Qiziqishlar",
      empty: "Hali hech narsa yo'q",
      emptyText: "Klubga qatnashing yoki jamoaga qo'shiling: shu yerda ko'rinadi.",
      attended: "Sessiyada qatnashdi",
      joinedClub: "Klubga qo'shildi",
      ideaPosted: "G'oya qo'ydi",
      joinedTeam: "Jamoaga qabul qilindi",
      ideaStatus: { pending: "tekshiruvda", open: "doskada", closed: "yopilgan" },
    },
    settings: {
      title: "Sozlamalar",
      reminders: "Eslatmalar",
      remindAll: "Telegram eslatmalari",
      remindAllText: "Klub sessiyasi kuni va saqlangan imkoniyat yopilishiga 3 kun qolganda bot xabar beradi.",
      telegram: "Telegram username",
      telegramText: "Faqat MIYA'da qabul qilingan jamoadoshingizga ko'rinadi. Botda /username buyrug'i bilan qo'shasiz.",
      telegramNone: "Qo'shilmagan",
      telegramSet: "Qo'shilgan",
      data: "Biz nimani saqlaymiz",
      dataItems: ["Telegram ID", "Ism yoki laqab", "Yosh oralig'i", "Hudud", "Qiziqishlar"],
      dataNever: "Telefon, familiya, tug'ilgan sana, rasm va email saqlanmaydi.",
      theme: "Ko'rinish",
      themeRow: "Kunduzgi / tungi rejim",
      themeText: "Tizim sozlamasiga ergashadi. Tugma bilan almashtirish mumkin.",
      logout: "Chiqish",
      delete: "Akkauntni o'chirish",
      deleteText: "Akkaunt va barcha ma'lumotlaringiz butunlay o'chadi. Buni qaytarib bo'lmaydi.",
      deleteConfirm: "Ha, o'chirish",
      cancel: "Bekor qilish",
    },
  },
  cards: {
    today: {
      title: "Bugun",
      rows: [
        { title: "Speaking Club", sub: "18:00 · 6/10 sessiya", progress: 60 },
        { title: "Stipendiya arizasi", sub: "Yopilishiga 12 kun", progress: 0 },
      ],
    },
    reminders: {
      title: "Eslatmalar",
      label: "Bugungi sessiya",
      name: "Speaking Club",
      place: "Chilonzor, 3-xona",
      time: "18:00 – 19:30",
    },
    telegram: {
      title: "Telegram orqali kirish",
      steps: ["Botni oching", "4 ta savol", "Saytga qayting"],
      note: "Parol va telefon so'ralmaydi",
    },
    note: "Juma 18:00 — Speaking Club. QR tayyor bo'lsin!",
    club: {
      title: "Speaking Club",
      when: "Har juma · 18:00",
      place: "Toshkent",
      members: "24 a'zo",
      join: "Qo'shilish",
      attended: "Oxirgi sessiya",
      qr: "QR bilan tasdiqlandi",
      caption: "Klublar",
      text: "Real uchrashuvlar. Sessiyada QR skanerlaysiz, qatnashganingiz profilga yoziladi.",
    },
    opportunity: {
      title: "Yozgi IT maktabi",
      organizer: "Tashkilotchi nomi",
      type: "Dastur",
      age: "16–18 yosh",
      region: "Butun O'zbekiston",
      deadlineLabel: "Ariza oxirgi kuni",
      deadline: "30-noyabr",
      link: "Rasmiy sahifa",
      verified: "Tekshirildi: 28-oktabr",
      caption: "Imkoniyatlar",
      text: "Qo'lda tekshirilgan dasturlar: muddat, shartlar va rasmiy manba bilan.",
    },
    idea: {
      title: "Maktab uchun kitob almashish boti",
      problem: "Kitoblar javonda turibdi, o'qimoqchilar esa topa olmaydi.",
      roles: ["Dizayner", "Dasturchi"],
      filled: "Jamoa: 1/3",
      join: "Qo'shilaman",
      caption: "MIYA",
      text: "G'oyangizni qo'ying, kerakli odamlarni toping va jamoa bo'ling.",
    },
  },

  // ---------- Server matnlari: Telegram bot, eslatmalar, kirish oqimi, server action xatolari ----------
  common: {
    other: "Boshqa",
    sample: "NAMUNA",
    report: "Xabar berish",
    save: "Saqlash",
    saved: "Saqlangan",
    cancel: "Bekor qilish",
    back: "Orqaga",
    loading: "Yuklanmoqda…",
  },
  opp: {
    types: {
      scholarship: "Stipendiya",
      program: "Dastur",
      competition: "Tanlov",
      internship: "Amaliyot",
      event: "Tadbir",
    },
    closes: "Ariza oxirgi kuni",
    closed: "Yopilgan",
    organizer: "Tashkilotchi",
    region: "Hudud",
    eligibility: "Kimlar uchun",
    verified: "Tekshirilgan sana",
    open: "Rasmiy sahifaga oʻtish",
    title: "Imkoniyatlar",
    lead: "Qoʻlda tekshirilgan dastur, stipendiya va tanlovlar. Har biri rasmiy manba bilan.",
    all: "Hammasi",
    filterType: "Turi",
    filterAge: "Yosh",
    filterRegion: "Hudud",
    empty: "Bu filtr boʻyicha imkoniyat topilmadi.",
    emptyAll: "Hozircha imkoniyat yoʻq.",
    reset: "Filtrni tozalash",
    save: "Saqlash",
    unsave: "Saqlanganlardan olib tashlash",
    saved: "Saqlangan",
    loginToSave: "Saqlash uchun kiring",
    closedNote: "Bu imkoniyatning ariza muddati tugagan.",
    reportLabel: "Xato yoki eskirgan",
    sourceNote: "Rasmiy manba",
    eligibilityTitle: "Kimlar uchun",
    daysLeft: (n: number) => `${n} kun qoldi`,
    noDeadline: "Muddatsiz",
  },
  report: {
    open: "Xabar berish",
    reason: "Nima notoʻgʻri?",
    send: "Yuborish",
    thanks: "Rahmat, xabaringiz qabul qilindi.",
    error: "Yuborib boʻlmadi. Birozdan keyin urinib koʻring.",
  },
  miya: {
    title: "MIYA",
    lead: "Gʻoyani yoz, kerakli odamlarni top, jamoa tuz. Gʻoyalar koʻrinishidan oldin tekshiriladi.",
    newIdea: "Gʻoya qoʻyish",
    loginToPost: "Gʻoya qoʻyish uchun kiring",
    empty: "Hozircha tasdiqlangan gʻoya yoʻq.",
    emptyText: "Birinchi boʻlib gʻoyangizni yozing.",
    needed: "Kerakli rollar",
    problem: "Qanday muammoni hal qiladi",
    description: "Gʻoya haqida",
    groupUnder18: "13–17 yosh guruhi",
    groupAdult: "18+ guruhi",
    author: "Muallif",
    form: {
      title: "Yangi gʻoya",
      lead: "Gʻoyangiz moderator tekshirgach doskada koʻrinadi.",
      fTitle: "Sarlavha",
      fTitleHint: "3–80 belgi",
      fProblem: "Qanday muammoni hal qiladi?",
      fProblemHint: "10–500 belgi",
      fDescription: "Gʻoya haqida batafsil",
      fDescriptionHint: "10–2000 belgi",
      fRoles: "Qanday odamlar kerak?",
      submit: "Tekshiruvga yuborish",
      errorLength: "Maydonlarni toʻldiring va uzunlikni tekshiring.",
      errorLimit: "Tekshiruvda 3 ta gʻoyangiz bor. Biri tasdiqlangach yangisini yozishingiz mumkin.",
      errorRate: "Juda koʻp urinish. Birozdan keyin qayta urinib koʻring.",
      sentTitle: "Gʻoya yuborildi",
      sentText: "Moderator tekshirgach doskada paydo boʻladi. Holatini profilda koʻrasiz.",
    },
    pendingNote: "Bu gʻoya hali tekshiruvda: faqat siz koʻrasiz.",
    closedNote: "Bu gʻoya yopilgan.",
    join: {
      title: "Qoʻshilaman",
      role: "Qaysi rolda?",
      message: "Nega aynan siz? (qisqa)",
      submit: "Soʻrov yuborish",
      sent: "Soʻrovingiz yuborildi. Muallif javob bergach Telegram botdan xabar olasiz.",
      accepted: "Soʻrovingiz qabul qilindi. Bogʻlanish uchun Telegram botni tekshiring.",
      declined: "Bu safar soʻrov qabul qilinmadi.",
      pending: "Soʻrovingiz koʻrib chiqilmoqda.",
      sameGroupOnly: "Soʻrov yuborish faqat oʻz yosh guruhingiz ichida mumkin.",
      loginToJoin: "Qoʻshilish uchun kiring",
      own: "Bu sizning gʻoyangiz.",
    },
    owner: {
      requests: "Qoʻshilish soʻrovlari",
      none: "Hozircha soʻrov yoʻq.",
      accept: "Qabul qilish",
      decline: "Rad etish",
      close: "Gʻoyani yopish",
      roleOf: (role: string) => `Rol: ${role}`,
    },
  },
  reminders: {
    session: (club: string, topic: string, time: string) =>
      `Bugun klub sessiyasi: ${club}. Mavzu: ${topic}. Vaqti: ${time}.`,
    closing: (title: string, days: number) =>
      `Saqlagan imkoniyatingiz yopilishiga ${days} kun qoldi: ${title}.`,
    stopHint: "Eslatmalarni oʻchirish: /eslatma",
  },
  auth: {
    title: "Telegram orqali kirish",
    lead: "Parol ham, telefon raqami ham kerak emas. Telegram botda 4 ta qisqa savolga javob berasiz, shu bilan tayyor.",
    start: "Telegram botni ochish",
    waitingTitle: "Telegramda tasdiqlang",
    waitingText: "Bot ochilgach «Start» bosing va savollarga javob bering. Tugagach shu sahifa oʻzi davom etadi.",
    openBot: "Botni ochish",
    expired: "Havolaning muddati tugadi. Qaytadan urinib koʻring.",
    retry: "Qaytadan",
    notConfigured: "Telegram bot hali sozlanmagan.",
    loggedInAs: "Siz kirgansiz",
  },
  settings: {
    title: "Sozlamalar",
    reminders: "Telegram eslatmalari",
    remindersOn: "Yoqilgan",
    remindersOff: "Oʻchirilgan",
    toggleReminders: "Eslatmalarni almashtirish",
    dangerTitle: "Akkauntni oʻchirish",
    dangerText:
      "Ismingiz, yosh oraligʻingiz, hududingiz, qiziqishlaringiz, klub va gʻoyalaringiz butunlay oʻchiriladi. Buni qaytarib boʻlmaydi.",
    confirmLabel: "Tushundim, oʻchirilsin",
    delete: "Akkauntni butunlay oʻchirish",
  },
  bot: {
    welcomeBack: "Qaytganingiz bilan! Saytga qaytib, kirishni davom ettiring.",
    welcomeNoToken: "Salom! Yoshlar Base botiga xush kelibsiz. Kirish uchun saytdagi «Telegram orqali kirish» tugmasidan foydalaning.",
    askName: (suggested: string) =>
      `Salom! Avval tanishib olamiz. Sizni qanday chaqiraylik? Telegramdagi ismingiz: ${suggested}. Shuni tanlang yoki laqab yozing.`,
    chooseName: (name: string) => `${name} deb chaqirilsin`,
    badName: "Ism faqat harflardan iborat boʻlsin (1–40 belgi). Havola, @ va raqamlar mumkin emas. Qaytadan yozing.",
    askAge: "Yosh oraligʻingiz?",
    tooYoung: "13 dan kichik boʻlsangiz hozircha roʻyxatdan oʻta olmaysiz. Hech qanday maʼlumot saqlanmadi.",
    under13: "13 dan kichikman",
    askRegion: "Qaysi hududdansiz?",
    askInterests: "Qiziqishlaringizni tanlang (bir nechta mumkin), keyin «Tayyor» bosing.",
    interestsDone: "Tayyor",
    done: "Tayyor! Saytga qayting: kirish avtomatik tasdiqlanadi.\n\nIxtiyoriy: /username @ismingiz yozsangiz, MIYA'da qabul qilingan jamoadoshingiz sizga Telegramda yoza oladi.",
    expiredLogin: "Bu kirish havolasining muddati tugagan. Saytdan qaytadan boshlang.",
    newRequest: (title: string) => `Gʻoyangizga yangi qoʻshilish soʻrovi keldi: «${title}». Saytda koʻrib chiqing.`,
    ideaApproved: (title: string) => `Gʻoyangiz tasdiqlandi va doskada koʻrinmoqda: «${title}».`,
    accepted: (title: string, nameHtml: string, username: string | null) =>
      `Jamoa tuzildi! «${title}» gʻoyasi boʻyicha bogʻlanish: ${nameHtml}${username ? ` (@${username})` : ""}. Telegram chatida yozishingiz mumkin.`,
    privateOnly: "Iltimos, botga shaxsiy xabarda yozing.",
    useButtons: "Iltimos, tugmalardan birini tanlang.",
    usernameSet: (u: string) => `Saqlandi: @${u}. Faqat MIYA'da soʻrovingiz qabul qilingan odamga koʻrsatiladi. Olib tashlash: /username`,
    usernameRemoved: "Username olib tashlandi.",
    usernameBad: "Username notoʻgʻri. Masalan: /username @ismingiz (5–32 belgi: harf, raqam, pastki chiziq).",
    usernameHelp: "Ixtiyoriy: /username @ismingiz yozsangiz, qabul qilingan jamoadoshingiz sizga Telegramda yoza oladi. Yozmasangiz ham boʻladi.",
    remindersOn: "Eslatmalar yoqildi.",
    remindersOff: "Eslatmalar oʻchirildi.",
  },
  club: {
    title: "Klublar",
    lead: "Real klublar: qoʻshiling va sessiyaga qatnashing.",
    schedule: "Jadval",
    organizer: "Tashkilotchi",
    sessions: "Kelayotgan sessiyalar",
    noSessions: "Yaqin sessiya hozircha yoʻq.",
    join: "Klubga qoʻshilish",
    leave: "Klubdan chiqish",
    member: "Siz aʼzosiz",
    loginToJoin: "Qoʻshilish uchun kiring",
    empty: "Hozircha klub yoʻq.",
    notFound: "Klub topilmadi.",
    checkin: {
      title: "Sessiyaga qatnashish",
      loginPrompt: "Qatnashganingizni tasdiqlash uchun avval kiring.",
      confirm: "Qatnashdim",
      done: "Qatnashganingiz yozildi. Profilingizda koʻrinadi.",
      already: "Siz bu sessiyaga allaqachon qatnashgansiz.",
      closed: "Bu sessiya uchun tasdiqlash vaqti hozir ochiq emas.",
      invalid: "Kod notoʻgʻri.",
      toProfile: "Profilga oʻtish",
    },
    qrLabel: "QR kod",
    qrHint: "Telefon kamerasi bilan skanerlang va qatnashganingizni tasdiqlang.",
  },
  mod: {
    newIdea: (group: string) => `Yangi g'oya moderatsiyada · ${group}`,
    problem: "Muammo",
    idea: "G'oya",
    roles: "Rollar",
    author: "Muallif",
    approve: "✅ Tasdiqlash",
    reject: "❌ Rad etish",
    approved: "✅ Tasdiqlandi: doskada ko'rinadi.",
    rejected: "❌ Rad etildi.",
    report: (type: string) => `Shikoyat · ${type}`,
    reason: "Sabab",
    hide: "Yashirish",
    dismiss: "Ko'rib chiqildi",
    hidden: "🙈 Yashirildi: saytda ko'rinmaydi.",
    dismissed: "👌 Ko'rib chiqildi, o'zgarishsiz.",
    entity: { opportunity: "Imkoniyat", club: "Klub", idea: "G'oya" },
    already: "Bu allaqachon ko'rib chiqilgan.",
    queueEmpty: "Navbat bo'sh: tekshiruvdagi g'oya ham, ochiq shikoyat ham yo'q.",
    queueHead: (ideas: number, reports: number) => `Navbat: ${ideas} ta g'oya, ${reports} ta shikoyat.`,
    ownerRejected: (title: string) => `«${title}» g'oyangiz bu safar doskaga chiqmadi. Qoidalarni tekshirib, qayta yozishingiz mumkin.`,
  },
} as const;
