// Barcha UI matnlari shu yerda (o'zbekcha, lotin). Keyin ru qo'shish oson bo'ladi.
export const REGIONS = [
  "Toshkent shahri",
  "Toshkent viloyati",
  "Andijon",
  "Buxoro",
  "Fargʻona",
  "Jizzax",
  "Xorazm",
  "Namangan",
  "Navoiy",
  "Qashqadaryo",
  "Qoraqalpogʻiston",
  "Samarqand",
  "Sirdaryo",
  "Surxondaryo",
] as const;

export const INTERESTS = [
  { key: "tech", label: "Texnologiya" },
  { key: "business", label: "Tadbirkorlik" },
  { key: "languages", label: "Tillar" },
  { key: "science", label: "Fan" },
  { key: "art", label: "Sanʼat" },
  { key: "sport", label: "Sport" },
  { key: "volunteering", label: "Volontyorlik" },
  { key: "study-abroad", label: "Chet elda oʻqish" },
] as const;

export const t = {
  brand: "Yoshlar Base",
  common: {
    sample: "NAMUNA",
    report: "Xabar berish",
    save: "Saqlash",
    saved: "Saqlangan",
    cancel: "Bekor qilish",
    back: "Orqaga",
    loading: "Yuklanmoqda…",
  },
  nav: {
    home: "Bosh sahifa",
    clubs: "Klublar",
    opportunities: "Imkoniyatlar",
    miya: "MIYA",
    profile: "Profil",
    login: "Telegram orqali kirish",
    logout: "Chiqish",
  },
  landing: {
    title: "Qilishga arziydigan ishlarni shu yerdan top.",
    lead: "Klubga qoʻshil, ishonchli imkoniyatni top, gʻoyangni jamoaga aylantir.",
    ctaPrimary: "Imkoniyatlarni koʻrish",
    ctaSecondary: "Telegram orqali kirish",
    pillars: [
      { name: "Klublar", text: "Haftalik uchrashuvlarga qoʻshil va sessiyaga qatnash." },
      { name: "Imkoniyatlar", text: "Qoʻlda tekshirilgan dastur va tanlovlar, rasmiy havola bilan." },
      { name: "MIYA", text: "Gʻoyangni yoz, kerakli odamlarni top, jamoa tuz." },
    ],
    soonTitle: "Yaqinda",
    soonText: "Hozircha namunaviy kartalar. Haqiqiy maʼlumot tez orada.",
  },
  opp: {
    types: {
      scholarship: "Stipendiya",
      program: "Dastur",
      competition: "Tanlov",
      internship: "Amaliyot",
      event: "Tadbir",
    },
    closes: "Ariza oxirgi kuni",
    closed: "Yopilgan",
    organizer: "Tashkilotchi",
    region: "Hudud",
    eligibility: "Kimlar uchun",
    verified: "Tekshirilgan sana",
    open: "Rasmiy sahifaga oʻtish",
  },
  club: {
    schedule: "Jadval",
  },
  auth: {
    title: "Telegram orqali kirish",
    lead: "Parol ham, telefon raqami ham kerak emas. Telegram botda 4 ta qisqa savolga javob berasiz, shu bilan tayyor.",
    start: "Telegram botni ochish",
    waitingTitle: "Telegramda tasdiqlang",
    waitingText: "Bot ochilgach «Start» bosing va savollarga javob bering. Tugagach shu sahifa oʻzi davom etadi.",
    openBot: "Botni ochish",
    expired: "Havolaning muddati tugadi. Qaytadan urinib koʻring.",
    retry: "Qaytadan",
    notConfigured: "Telegram bot hali sozlanmagan.",
    loggedInAs: "Siz kirgansiz",
  },
  settings: {
    title: "Sozlamalar",
    reminders: "Telegram eslatmalari",
    remindersOn: "Yoqilgan",
    remindersOff: "Oʻchirilgan",
    toggleReminders: "Eslatmalarni almashtirish",
    dangerTitle: "Akkauntni oʻchirish",
    dangerText:
      "Ismingiz, yosh oraligʻingiz, hududingiz, qiziqishlaringiz, klub va gʻoyalaringiz butunlay oʻchiriladi. Buni qaytarib boʻlmaydi.",
    confirmLabel: "Tushundim, oʻchirilsin",
    delete: "Akkauntni butunlay oʻchirish",
  },
  bot: {
    welcomeBack: "Qaytganingiz bilan! Saytga qaytib, kirishni davom ettiring.",
    welcomeNoToken: "Salom! Yoshlar Base botiga xush kelibsiz. Kirish uchun saytdagi «Telegram orqali kirish» tugmasidan foydalaning.",
    askName: (suggested: string) =>
      `Salom! Avval tanishib olamiz. Sizni qanday chaqiraylik? Telegramdagi ismingiz: ${suggested}. Shuni tanlang yoki laqab yozing.`,
    chooseName: (name: string) => `${name} deb chaqirilsin`,
    badName: "Ism faqat harflardan iborat boʻlsin (1–40 belgi). Havola, @ va raqamlar mumkin emas. Qaytadan yozing.",
    askAge: "Yosh oraligʻingiz?",
    tooYoung: "13 dan kichik boʻlsangiz hozircha roʻyxatdan oʻta olmaysiz. Hech qanday maʼlumot saqlanmadi.",
    under13: "13 dan kichikman",
    askRegion: "Qaysi hududdansiz?",
    askInterests: "Qiziqishlaringizni tanlang (bir nechta mumkin), keyin «Tayyor» bosing.",
    interestsDone: "Tayyor",
    done: "Tayyor! Saytga qayting: kirish avtomatik tasdiqlanadi.",
    expiredLogin: "Bu kirish havolasining muddati tugagan. Saytdan qaytadan boshlang.",
    privateOnly: "Iltimos, botga shaxsiy xabarda yozing.",
    useButtons: "Iltimos, tugmalardan birini tanlang.",
    remindersOn: "Eslatmalar yoqildi.",
    remindersOff: "Eslatmalar oʻchirildi.",
  },
  today: {
    hello: (name: string) => `Salom, ${name}`,
    lead: "Bugun uchun muhim narsalar shu yerda.",
    nextSessions: "Keyingi sessiyalar",
    nextSessionsEmpty: "Hali hech qaysi klubga qoʻshilmagansiz.",
    nextSessionsEmptyText: "Klubga qoʻshiling, sessiya vaqti shu yerda koʻrinadi.",
    browseClubs: "Klublarni koʻrish",
    savedTitle: "Saqlangan imkoniyatlar",
    savedEmpty: "Hozircha saqlanganlar yoʻq.",
    savedEmptyText: "Yoqqan imkoniyatni saqlang, muddati yaqinlashganda eslatamiz.",
    browseOpps: "Imkoniyatlarni koʻrish",
    ideasTitle: "Yangi gʻoyalar",
    ideasEmpty: "Hozircha yangi gʻoya yoʻq.",
    ideasEmptyText: "Birinchi boʻlib oʻz gʻoyangizni yozing, jamoa toping.",
    browseIdeas: "MIYA doskasi",
    at: "Joyi",
  },
  profile: {
    title: "Profil",
    sub: "Bu yerda faqat siz haqiqatan qilgan ishlar chiqadi. Hammasi avtomatik toʻladi.",
    age: "Yosh oraligʻi",
    region: "Hudud",
    interests: "Qiziqishlar",
    settings: "Sozlamalar",
    statsClubs: "Klub",
    statsAttended: "Qatnashgan sessiya",
    statsIdeas: "Gʻoya",
    statsTeam: "Jamoa",
    clubsTitle: "Klublar",
    attendedTitle: "Qatnashgan sessiyalar",
    ideasTitle: "Gʻoyalarim",
    teamsTitle: "Jamoalar",
    ideaStatus: { pending: "Tekshiruvda", open: "Ochiq", closed: "Yopilgan" } as const,
    joinedAs: (role: string) => `Rol: ${role}`,
    emptyTitle: "Profilingiz hali boʻsh",
    emptyText: "Klubga qoʻshiling, sessiyaga qatnashing yoki gʻoya yozing. Qilgan ishlaringiz shu yerda paydo boʻladi.",
  },
  gallery: {
    title: "Komponentlar",
    intro: "Dizayn poydevori: ranglar, shrift va asosiy komponentlar.",
  },
} as const;
